### ISSUE TITLE
May 15th 2018

### ISSUE THREAD

**Issue by ynotdraw** [ynotdraw/ember-dallas-meetup#1]
Thumbs up if you made it!

Please rate your experience with Ember, so we can ensure the content fits all levels.

[![](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Beginner)](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Beginner/vote)
[![](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Intermediate)](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Intermediate/vote)
[![](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Advanced)](https://api.gh-polls.com/poll/01CDJ5DYA3ZTHS9S5X00YMYBRZ/Advanced/vote)

Feel free to comment on what you're looking to learn from this meetup as well!

**Comment by inscroggnito** [comment]
Great job, Tony!!!

**Comment by ynotdraw** [comment]
Slides from my talk: https://ynotdraw.github.io/ember-decorators/index.html#/
`ember-decorators` repo: https://github.com/ynotdraw/ember-github-decorators

Thanks for coming!
